/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	rdsv1 "github.com/rds-code-generation/pkg/apis/rds/v1"
	versioned "github.com/rds-code-generation/pkg/client/clientset/versioned"
	internalinterfaces "github.com/rds-code-generation/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/rds-code-generation/pkg/client/listers/rds/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MysqlInformer provides access to a shared informer and lister for
// Mysqls.
type MysqlInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.MysqlLister
}

type mysqlInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMysqlInformer constructs a new informer for Mysql type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMysqlInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMysqlInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMysqlInformer constructs a new informer for Mysql type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMysqlInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RdsV1().Mysqls(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RdsV1().Mysqls(namespace).Watch(options)
			},
		},
		&rdsv1.Mysql{},
		resyncPeriod,
		indexers,
	)
}

func (f *mysqlInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMysqlInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *mysqlInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rdsv1.Mysql{}, f.defaultInformer)
}

func (f *mysqlInformer) Lister() v1.MysqlLister {
	return v1.NewMysqlLister(f.Informer().GetIndexer())
}
